import 'package:flutter/material.dart';
import '../../domain/entities/workshop.dart';
import '../widgets/feature_page.dart';
import '../widgets/order_form.dart';

class AluminumHubScreen extends StatelessWidget { const AluminumHubScreen({required this.workshop, required this.onNewOrder, super.key}); final Workshop workshop; final VoidCallback onNewOrder; @override Widget build(BuildContext context) => FeaturePage(title: 'رئيسية الألمنيوم', subtitle: workshop.tagline, icon: workshop.icon, workshop: workshop, actions: [const FeatureAction(title: 'معرض الكلادينج والزجاج', detail: 'واجهات عازلة وموديلات حديثة', icon: Icons.photo_library), FeatureAction(title: 'مواصفات ألمنيوم جديدة', detail: 'حدد القطاع والزجاج واللون', icon: Icons.add_task, onTap: onNewOrder)]); }
class AluminumPortfolioScreen extends StatelessWidget { const AluminumPortfolioScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'معرض أعمال الكلادينج', subtitle: 'قطاعات وألوان زجاج قابلة للتخصيص', icon: Icons.photo_library, workshop: workshop, actions: List.generate(4, (i) => FeatureAction(title: 'واجهة ألمنيوم ${i + 1}', detail: 'زجاج عازل وقطاع حراري', icon: Icons.window))); }
class AluminumOrderScreen extends StatelessWidget { const AluminumOrderScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => OrderFormPage(workshop: workshop); }
class AluminumBalancerScreen extends StatelessWidget { const AluminumBalancerScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'التوزيع الجغرافي', subtitle: 'العثور على ورشة تمتلك المعدات المناسبة', icon: Icons.location_searching, workshop: workshop, actions: const [FeatureAction(title: 'ورشة التيسير', detail: 'كابس الزاوية الآلي متاح، 91% ملاءمة', icon: Icons.factory), FeatureAction(title: 'ورشة العزل', detail: 'المسافة 18 كم، 76% ملاءمة', icon: Icons.map)]); }
class AluminumTimelineScreen extends StatelessWidget { const AluminumTimelineScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'خط تجميع الألمنيوم', subtitle: 'اختبارات القياس والعزل قبل التسليم', icon: Icons.timeline, workshop: workshop, actions: const [FeatureAction(title: 'قص القطاعات', detail: 'مكتمل', icon: Icons.check_circle), FeatureAction(title: 'التجميع والكبس', detail: 'قيد التنفيذ', icon: Icons.construction), FeatureAction(title: 'اختبار العزل', detail: 'قيد الانتظار', icon: Icons.pending)]); }
class AluminumTechScreen extends StatelessWidget { const AluminumTechScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'واجهة الفني السريعة', subtitle: 'أدوات الفني والماسح البصري', icon: Icons.qr_code_scanner, workshop: workshop, actions: const [FeatureAction(title: 'مسح باركود القطاع', detail: 'قراءة مواصفات الخامة', icon: Icons.qr_code_scanner), FeatureAction(title: 'فحص الإغلاق', detail: 'تسجيل نتيجة الاختبار', icon: Icons.fact_check), FeatureAction(title: 'إضافة ملاحظة', detail: 'إرسال تنبيه للفريق', icon: Icons.note_add)]); }
class AluminumInventoryScreen extends StatelessWidget { const AluminumInventoryScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'مستودع القطاعات', subtitle: 'متابعة قطاعات الألمنيوم والزجاج', icon: Icons.inventory_2, workshop: workshop, actions: const [FeatureAction(title: 'قطاعات حرارية', detail: '64 قطعة متاحة', icon: Icons.view_agenda), FeatureAction(title: 'ألواح الزجاج العازل', detail: '24 لوحًا متاحًا', icon: Icons.crop_square)]); }
class AluminumWarrantyScreen extends StatelessWidget { const AluminumWarrantyScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'الفحص والضمان الرقمي', subtitle: 'شهادة جودة قابلة للتتبع', icon: Icons.verified, workshop: workshop, actions: const [FeatureAction(title: 'اختبار العزل', detail: '96%، اجتياز بنجاح', icon: Icons.verified_user), FeatureAction(title: 'الضمان', detail: 'خمس سنوات معتمدة', icon: Icons.policy), FeatureAction(title: 'تحميل الشهادة', detail: 'ملف PDF موثق', icon: Icons.download)]); }
