import 'package:flutter/material.dart';
import '../../domain/entities/workshop.dart';
import '../widgets/feature_page.dart';
import '../widgets/order_form.dart';

class BlacksmithHubScreen extends StatelessWidget { const BlacksmithHubScreen({required this.workshop, required this.onNewOrder, super.key}); final Workshop workshop; final VoidCallback onNewOrder; @override Widget build(BuildContext context) => FeaturePage(title: 'رئيسية الحدادة', subtitle: workshop.tagline, icon: workshop.icon, workshop: workshop, actions: [const FeatureAction(title: 'معرض الحديد المعشق', detail: 'بوابات، درابزين، وأعمال ليزر', icon: Icons.photo_library), FeatureAction(title: 'طلب حديد مخصص', detail: 'حدد المقاسات ونوع التشطيب', icon: Icons.add_task, onTap: onNewOrder)]); }
class BlacksmithPortfolioScreen extends StatelessWidget { const BlacksmithPortfolioScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'معرض الحديد المعشق', subtitle: 'نماذج قص وتشكيل معدنية', icon: Icons.photo_library, workshop: workshop, actions: List.generate(4, (i) => FeatureAction(title: 'تصميم حديد ${i + 1}', detail: 'قص ليزر وتشطيب حراري', icon: Icons.grid_view))); }
class BlacksmithOrderScreen extends StatelessWidget { const BlacksmithOrderScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => OrderFormPage(workshop: workshop); }
class BlacksmithBalancerScreen extends StatelessWidget { const BlacksmithBalancerScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'سعة الورش والقدرات', subtitle: 'مقارنة ضغط ماكينات القص واللحام', icon: Icons.insights, workshop: workshop, actions: const [FeatureAction(title: 'مصنع الفولاذ الفني', detail: '88% ملاءمة، ماكينة الليزر متاحة', icon: Icons.factory), FeatureAction(title: 'ورشة التشكيل', detail: '64% ملاءمة، انتظار يومين', icon: Icons.speed)]); }
class BlacksmithTimelineScreen extends StatelessWidget { const BlacksmithTimelineScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'الخط الزمني للتشكيل', subtitle: 'متابعة القص واللحام والطلاء', icon: Icons.timeline, workshop: workshop, actions: const [FeatureAction(title: 'قص الليزر', detail: 'مكتمل', icon: Icons.check_circle), FeatureAction(title: 'تجميع ولحام', detail: 'قيد التنفيذ', icon: Icons.local_fire_department), FeatureAction(title: 'الطلاء الحراري', detail: 'قيد الانتظار', icon: Icons.pending)]); }
class BlacksmithCraftsmanScreen extends StatelessWidget { const BlacksmithCraftsmanScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'لوحة الأكشن للحداد', subtitle: 'أفعال سريعة في بيئة العمل', icon: Icons.local_fire_department, workshop: workshop, actions: const [FeatureAction(title: 'بدء عمليات اللحام', detail: 'تحديث حالة الطلب', icon: Icons.play_arrow), FeatureAction(title: 'جاهز للطلاء', detail: 'إرسال المرحلة التالية', icon: Icons.brush), FeatureAction(title: 'جرد مستودع الحديد', detail: 'فتح الخامات والأقراص', icon: Icons.warehouse)]); }
class BlacksmithInventoryScreen extends StatelessWidget { const BlacksmithInventoryScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'حديد التسليح والخامات', subtitle: 'إدارة مخزون المعدن وأقراص القطع', icon: Icons.inventory_2, workshop: workshop, actions: const [FeatureAction(title: 'ألواح الحديد', detail: '31 لوحًا متاحًا', icon: Icons.inventory), FeatureAction(title: 'أقراص القطع', detail: '12 قرصًا، كمية جيدة', icon: Icons.circle)]); }
class BlacksmithDeliveryScreen extends StatelessWidget { const BlacksmithDeliveryScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'تنسيق التسليم والتركيب', subtitle: 'حجز موعد النقل وفريق التركيب', icon: Icons.local_shipping, workshop: workshop, actions: const [FeatureAction(title: 'الموقع المسجل', detail: 'حي الورود، شارع الحرفيين', icon: Icons.location_on), FeatureAction(title: 'موعد التركيب', detail: 'الأحد 25 أغسطس، 09:00 - 12:00', icon: Icons.event_available)]); }
