import 'package:flutter/material.dart';
import '../../domain/entities/workshop.dart';
import '../widgets/feature_page.dart';
import '../widgets/order_form.dart';

class CarpentryHubScreen extends StatelessWidget {
  const CarpentryHubScreen({required this.workshop, required this.onNewOrder, super.key});
  final Workshop workshop;
  final VoidCallback onNewOrder;
  @override
  Widget build(BuildContext context) => FeaturePage(title: 'رئيسية النجارة', subtitle: workshop.tagline, icon: workshop.icon, workshop: workshop, actions: [const FeatureAction(title: 'معرض أعمال النجارة', detail: 'نماذج أبواب وأثاث حسب الطلب', icon: Icons.photo_library), FeatureAction(title: 'طلب تفصيل جديد', detail: 'ابدأ مواصفات مشروعك الآن', icon: Icons.add_task, onTap: onNewOrder)]);
}

class CarpentryPortfolioScreen extends StatelessWidget { const CarpentryPortfolioScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'معرض أعمال النجارة', subtitle: 'نماذج مختارة قابلة للتخصيص', icon: Icons.photo_library, workshop: workshop, actions: List.generate(4, (i) => FeatureAction(title: 'نموذج خشبي ${i + 1}', detail: 'خشب طبيعي، تشطيب يدوي، يبدأ من 850 ر.س', icon: Icons.chair))); }
class CarpentryOrderScreen extends StatelessWidget { const CarpentryOrderScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => OrderFormPage(workshop: workshop); }
class CarpentryBalancerScreen extends StatelessWidget { const CarpentryBalancerScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'موازنة الأحمال الذكية', subtitle: 'اختيار الورشة الأنسب جغرافيًا وتشغيليًا', icon: Icons.insights, workshop: workshop, actions: const [FeatureAction(title: 'ورشة الأرز', detail: '92% ملاءمة، التسليم خلال 4 أيام', icon: Icons.check_circle), FeatureAction(title: 'ورشة الإتقان', detail: '78% ملاءمة، التسليم خلال 6 أيام', icon: Icons.speed)]); }
class CarpentryTimelineScreen extends StatelessWidget { const CarpentryTimelineScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'الخط الزمني للإنتاج', subtitle: 'تتبع كل مرحلة من الاستلام إلى التسليم', icon: Icons.timeline, workshop: workshop, actions: const [FeatureAction(title: 'استلام الطلب', detail: 'مكتمل', icon: Icons.check_circle), FeatureAction(title: 'تجهيز الخشب', detail: 'مكتمل', icon: Icons.check_circle), FeatureAction(title: 'التنفيذ والفحص', detail: 'قيد الانتظار', icon: Icons.pending)]); }
class CarpentryCraftsmanScreen extends StatelessWidget { const CarpentryCraftsmanScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'لوحة الحرفي السريعة', subtitle: 'إجراءات يومية سريعة داخل الورشة', icon: Icons.build_circle, workshop: workshop, actions: const [FeatureAction(title: 'تحديث حالة الطلب', detail: 'تغيير مرحلة التنفيذ', icon: Icons.update), FeatureAction(title: 'فحص الجودة', detail: 'تسجيل نتيجة الفحص', icon: Icons.fact_check), FeatureAction(title: 'إضافة ملاحظة', detail: 'تدوين ملاحظة للعميل', icon: Icons.note_add)]); }
class CarpentryInventoryScreen extends StatelessWidget { const CarpentryInventoryScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'إدارة المواد الخام', subtitle: 'مخزون الأخشاب والمواد المساندة', icon: Icons.inventory_2, workshop: workshop, actions: const [FeatureAction(title: 'خشب زان / قطاعات', detail: '42 وحدة، آخر تحديث منذ ساعتين', icon: Icons.inventory), FeatureAction(title: 'مواد تثبيت وتشطيب', detail: '18 وحدة، كمية متوسطة', icon: Icons.category)]); }
class CarpentryReviewScreen extends StatelessWidget { const CarpentryReviewScreen({required this.workshop, super.key}); final Workshop workshop; @override Widget build(BuildContext context) => FeaturePage(title: 'تقييم جودة النجارة', subtitle: 'اعتماد جودة العمل بعد التسليم', icon: Icons.verified, workshop: workshop, actions: const [FeatureAction(title: 'شهادة جودة رقمية', detail: 'جميع مراحل العمل موثقة', icon: Icons.verified_user), FeatureAction(title: 'تقييم الورشة', detail: 'أضف تقييمك وملاحظاتك', icon: Icons.star_rate)]); }
